// Generated by Wrangler on Sat Aug 31 2024 13:22:41 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
  CLOUDFLARE_ACCOUNT_ID: string;
  R2_BUCKET_NAME: string;
  CLOUDFLARE_R2_ACCESS_KEY_ID: string;
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: string;
}
