name: Deploy site
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Add TypeScript as dev dependency
        run: yarn add --dev typescript

      - name: Build production files
        uses: borales/actions-yarn@v5
        with:
          cmd: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist
