name: Fix missing cover images in blog posts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit_message:
        type: string
        description: Commit message to use for this content build step
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan-mdx-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Scan MDX files and fetch missing images
        id: scan-and-fetch
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            # Find all .mdx files
            mdx_files=$(find src/content/blog -name "*.mdx")

            for file in $mdx_files
            do
              # Use gray-matter to check for coverImage
              if ! node -e "
                const matter = require('gray-matter');
                const fs = require('fs');
                const fileContents = fs.readFileSync('$file', 'utf8');
                const { data } = matter(fileContents);
                if (!data.coverImage) {
                  console.log('$file is missing coverImage');
                  process.exit(1);
                }
              "
              then
                echo "Warning: $file is missing coverImage frontmatter. Attempting to fetch from R2..."
                
                # Extract the date and slug from the file path
                dir_name=$(dirname "$file")
                base_name=$(basename "$dir_name")
                
                # Construct the R2 object key and local file path
                r2_key="portfolio/blog/cover/$base_name/image.webp"
                local_path="$dir_name/image.webp"
                
                # Use Wrangler to fetch the image from R2
                if wrangler r2 object get ${{ secrets.R2_BUCKET_NAME }}/$r2_key --file $local_path; then
                  echo "Successfully fetched image for $file"
                  
                  # Update the frontmatter with the new coverImage
                  sed -i '1s/^/---\ncoverImage: ".\/image.webp"\n---\n/' "$file"
                  echo "Updated frontmatter for $file"
                else
                  echo "Error: Failed to fetch image for $file"
                  exit 1
                fi
              fi
            done

            echo "All MDX files now have coverImage frontmatter"

      - name: Fix Formatting
        run: yarn format:write

      - name: Stage all changes
        run: |
          git add .
          git diff --staged --quiet || echo "CHANGES_EXIST=true" >> $GITHUB_ENV

      - name: Commit Changes
        if: env.CHANGES_EXIST == 'true'
        uses: planetscale/ghcommit-action@v0.1.33
        with:
          commit_message: ${{ github.event.inputs.commit_message || 'Update MDX frontmatter and fetch missing images' }}
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for commit errors
        if: env.CHANGES_EXIST == 'true'
        run: |
          if [ $? -ne 0 ]; then
            echo "Failed to commit changes. Check the logs for errors."
            exit 1
          fi

      - name: Report status
        if: failure()
        run: |
          echo "Some MDX files are missing coverImage frontmatter and images could not be fetched"
          exit 1
