name: Deploy site
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install project dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: dist

      - name: Install Fastly dependencies
        run: |
          cd compute-js
          npm install

      - name: fastly compute deploy
        uses: fastly/compute-actions@v5
        with:
          project_directory: compute-js
          comment: “Deployed via GitHub Actions”
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
