name: Deploy site
on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Notion and commit changes"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Install Fastly Compute types
        uses: borales/actions-yarn@v5
        with:
          cmd: add --dev @fastly/js-compute

      - name: Build production files
        uses: borales/actions-yarn@v5
        with:
          cmd: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: "compute-js"

      - name: fastly compute deploy
        uses: fastly/compute-actions@v8
        with:
          project_directory: compute-js
          comment: “Deployed via GitHub Actions”
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
