name: Commit Notion changes

on:
  workflow_dispatch:
    inputs:
      commit_message:
        type: string
        description: Commit message to use for this content build step
        required: false

jobs:
  commit:
    runs-on: ubuntu-24.04
    env:
      TZ: 'America/Los_Angeles'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Run Notion script
        uses: borales/actions-yarn@v5
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        with:
          cmd: notion-to-md

      - name: Fix Formatting
        uses: borales/actions-yarn@v5
        with:
          cmd: format:write

      - name: Stage all changes
        run: |
          git add .

      - name: Commit Changes
        uses: planetscale/ghcommit-action@v0.1.33
        with:
          commit_message: ${{ github.event.inputs.commit_message || 'Update from Notion' }}
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
