name: Commit Notion changes

on:
  workflow_dispatch:
    inputs:
      commit_message:
        type: string
        description: Commit message to use for this content build step
        required: false
  repository_dispatch:
    types:
      - notion

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Los_Angeles'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Notion script
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: yarn notion
        continue-on-error: true

      - name: Check for script errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Notion script failed. Check the logs for errors."
            exit 1
          fi

      - name: Fix Formatting
        run: yarn format:write

      - name: Stage all changes
        id: stage
        run: |
          git add .
          git diff --staged --quiet || echo "CHANGES_EXIST=true" >> $GITHUB_OUTPUT

      - name: Commit Changes
        if: ${{ steps.stage.outputs.CHANGES_EXIST == 'true' }}
        uses: planetscale/ghcommit-action@v0.1.33
        with:
          commit_message: ${{ github.event.inputs.commit_message || 'Update from Notion' }}
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for commit errors
        if: ${{ steps.stage.outputs.CHANGES_EXIST == 'true' }}
        run: |
          if [ $? -ne 0 ]; then
            echo "Failed to commit changes. Check the logs for errors."
            exit 1
          fi
